package com.legalai.backend.controller;

import com.legalai.backend.model.DocumentSummaryRequest;
import com.legalai.backend.model.KeywordSearchRequest;
import com.legalai.backend.model.LegalQaRequest;
import com.legalai.backend.model.StandardResponse;
import jakarta.validation.Valid;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
@RequestMapping("/api")
public class LegalAiController {

    @PostMapping("/search")
    public ResponseEntity<StandardResponse> keywordSearch(
            @Valid @org.springframework.web.bind.annotation.RequestBody KeywordSearchRequest request) {
        return ResponseEntity.ok(
                StandardResponse.success("search", Map.of(
                        "query", request.getQuery(),
                        "jurisdiction", request.getJurisdiction(),
                        "results", List.of(
                                Map.of("title", "Sample Statute Match", "citation", "IN-STAT-2020-11"),
                                Map.of("title", "Sample Case Match", "citation", "IN-CASE-2018-402")
                        ),
                        "crewAgents", List.of("Research Agent", "Citation Agent", "Verifier Agent")
                )));
    }

    @PostMapping("/qa")
    public ResponseEntity<StandardResponse> legalQa(
            @Valid @org.springframework.web.bind.annotation.RequestBody LegalQaRequest request) {
        return ResponseEntity.ok(
                StandardResponse.success("qa", Map.of(
                        "question", request.getQuestion(),
                        "answer", "This is a placeholder answer from the Crew AI Q&A agents.",
                        "confidence", "medium",
                        "crewAgents", List.of("Reasoning Agent", "Policy Agent", "Guardrails Agent")
                )));
    }

    @PostMapping(value = "/upload", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<StandardResponse> uploadDocument(
            @RequestParam("file") MultipartFile file,
            @RequestParam(value = "notes", required = false) String notes) {
        return ResponseEntity.ok(
                StandardResponse.success("upload", Map.of(
                        "fileName", file.getOriginalFilename(),
                        "size", file.getSize(),
                        "notes", notes,
                        "status", "received",
                        "crewAgents", List.of("Ingestion Agent", "Classifier Agent", "Security Agent")
                )));
    }

    @PostMapping("/summarize")
    public ResponseEntity<StandardResponse> summarize(
            @Valid @org.springframework.web.bind.annotation.RequestBody DocumentSummaryRequest request) {
        return ResponseEntity.ok(
                StandardResponse.success("summarize", Map.of(
                        "summary", "Placeholder summary generated by Crew AI summarization agents.",
                        "length", request.getLength(),
                        "crewAgents", List.of("Summarizer Agent", "Risk Agent", "Compliance Agent")
                )));
    }

    @GetMapping("/govt-formats")
    public ResponseEntity<StandardResponse> govtFormats() {
        return ResponseEntity.ok(
                StandardResponse.success("govt-formats", Map.of(
                        "formats", List.of(
                                Map.of("name", "Affidavit Template", "code", "IN-AFF-001"),
                                Map.of("name", "Rental Agreement Template", "code", "IN-REN-002"),
                                Map.of("name", "Power of Attorney Template", "code", "IN-POA-003")
                        ),
                        "crewAgents", List.of("Template Agent", "Formatter Agent", "Validation Agent")
                )));
    }
}
